### PR TITLE
Fix issue of missing choice dropdown in VSCode

### PR DESCRIPTION
**Pull request by PawelWozniak**
### What does this PR do?
Fix issue in snippets that choices are not recognised because of wrong snippet code.
Snippets fixed: staticmethod, method, field, constructor.

### What issues does this PR fix or reference?
#<Insert GitHub Issue>, @<Insert GUS WI>@

### Functionality Before
Snippet staticmethod has all choices displayed, selection menu is missing.
image

### Functionality After
Snippet staticmethod has dropdown selection
image

### CODE REVIEW

**Comment by PawelWozniak** [comment]
@randi274 Please merge this PR.

**Comment by randi274** [comment]
@PawelWozniak thanks for the reminder on this! I've got #3492 rebuilding now; once that's ready, we'll get it merged in and this closed out.

**Comment by randi274** [comment]
All set - thanks again for the contribution @PawelWozniak! We're just past this upcoming release now, but look for the change in the following release.

**Comment by PawelWozniak** [comment]
Thank you.

**Pull request closed without merging**
