### PR TITLE
Update deprecated workspace.rootPath method to getRootWorkspacePath

### PR DESCRIPTION
**Pull request by rvwatch**
### What does this PR do?
Replaces the deprecated workspace.rootPath method with the util getRootWorkspacePath() inside of the core extension. In a few conditionals, I used hasRootWorkspace() where appropriate. 

### What issues does this PR fix or reference?
@W-6003984@

### CODE REVIEW

**Comment by lcampos** [comment]
@rvwatch I know this is still a work in progress but I would advise on pausing it since PRs #1246 and #1259 will take care of most of the changes you're looking at doing.

**Comment by rvwatch** [comment]
> @rvwatch I know this is still a work in progress but I would advise on pausing it since PRs #1246 and #1259 will take care of most of the changes you're looking at doing.

Thanks for the head up @lcampos! I'm going to set the work item I have for this one to "waiting". Is there a particular PR (_1246 = W-5988755_ or _1259 = W-5856821_) that you'd prefer I set as the parent for this one?

**Comment by rvwatch** [comment]
@lcampos It looks like #1246 has been merged, but #1259 is still pending. Will that be merged soon?

FYI, I pulled #1259 into an updated version of the repo and there appear to be several places where the deprecated workspace.rootPath remains. I assumed I'd simply wait for 1259 to be merged and then update this PR with the changes but I wanted to surface that idea in case you'd prefer a different approach.

**Comment by lcampos** [comment]
@rvwatch both PRs are merged now. Feel free to update this PR with the rest of the changes you're looking at doing.

**Comment by rvwatch** [comment]
Not sure why this is showing 73 files changed. I pulled in the latest merged changes locally. It should only be showing 5 files that I've updated.

**Comment by rvwatch** [comment]
Ran into some rebase conflicts and ended up with some commit message duplication. Will clear those out during the squash/merge. Let me know if there's anyone specific I should request for review.

**Pull request merged**
