### PR TITLE
Update prettier.md

### PR DESCRIPTION
**Pull request by thejohncotton**
Remove period after npm install command for simplified copy/paste.

### What issues does this PR fix or reference?
#<Insert GitHub Issue>, @<Insert GUS WI>@

### Functionality Before
<insert gif and/or summary>

### Functionality After
<insert gif and/or summary>

### CODE REVIEW

**Comment by brpowell** [comment]
Thanks for submitting @thejohncotton. It is an awfully small period isn't it? Can see how that would result in a difficult copy+paste 😄 .

Screen Shot 2020-09-23 at 5 05 49 PM

Looping @ekapner in

**Comment by thejohncotton** [comment]
Thanks @brpowell it is likely more to do with style as it appears the markup is correct. The markdown text block does include the `Run:` and `.` when you double click. The removal of the . doesn't necessarily solve entirely but was my attempt to contribute in hopes of preventing friction for other devs.

**Comment by ekapner** [comment]
> Thanks for submitting @thejohncotton. It is an awfully small period isn't it? Can see how that would result in a difficult copy+paste 😄 .
> 
> Screen Shot 2020-09-23 at 5 05 49 PM
> 
> Looping @ekapner in

Could put the command on a separate line to avoid the period.

**Comment by ekapner** [comment]
> > Thanks for submitting @thejohncotton. It is an awfully small period isn't it? Can see how that would result in a difficult copy+paste 😄 .
> > Screen Shot 2020-09-23 at 5 05 49 PM
> > Looping @ekapner in
> 
> @brpowell Could put the command on a separate line to avoid the period. Do you need me to fix it?

**Comment by brpowell** [comment]
@ekapner sounds good to me, and that'd be great

**Comment by brpowell** [comment]
Closing since change was merged in #2586, thank you for the contribution @thejohncotton! The doc change will be published this week with the new version of the extensions.

**Pull request closed without merging**
