### PR TITLE
feat: add e2e run on windows

### PR DESCRIPTION
**Pull request by RitamAgrawal**
### What does this PR do?
This PR modifies the existing End To End workflow to run tests on windows-latest in addition to macos-latest.
### What issues does this PR fix or reference?
 @W-13751849@

### Functionality Before
End To End Test were running only on macOs-latest.

### Functionality After
End To End Test runs on two remote env - macos- latest & windows-latest

### CODE REVIEW

**Comment by RitamAgrawal** [comment]
Ran End To end Tests using this branch and it does kick off two jobs. [Here](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5548960366) is the Github Action run.

**Review by gbockus-sf — APPROVED** [review]
:excited: :shipit:

**Review by CristiCanizales — APPROVED** [review]
🥳

**Comment by RitamAgrawal** [comment]
Tests on windows and mac os env should run independently irrespective of each other's success or failure. So reverting it.

**Pull request merged**
