### PR TITLE
Set default project create template to standard

### PR DESCRIPTION
**Pull request by ntotten**
### What does this PR do?
Updates the project create to use the standard template

### What issues does this PR fix or reference?
#1090

### CODE REVIEW

**Comment by ruthemmanuelle** [comment]
Thanks for updating this, @ntotten . The Salesforce release notes will say that the `standard` template becomes the default (in Salesforce CLI and Salesforce Extensions for VS Code) at R2. I think we should wait until then to merge this PR. We have docs and Trailhead content that refer to the old project structure, and they'll be wrong if we merge this now. Cc: @lcampos

**Comment by ntotten** [comment]
I don't want to wait in VS Code. This isn't going to break documentation or tutorials because the commands don't change, the only difference is that the template will have more stuff in it. The reason we are waiting in CLI is that we have a policy of introducing breaking changes only at R2, we don't have such a policy for VS Code - nor should we.

Let's update the release notes to reflect that the change is only the default in CLI at R2.

**Comment by ruthemmanuelle** [comment]
Here are a couple of Trailhead units that will be wrong if we merge this:
- https://trailhead.salesforce.com/content/learn/projects/find-and-fix-bugs-with-apex-replay-debugger/apex-replay-debugger-set-up-debugger
- https://trailhead.salesforce.com/content/learn/projects/quickstart-vscode-salesforce/use-vscode-for-salesforce

There might be others. Those are just the ones I know about off the top of my head.

**Comment by lcampos** [comment]
Changes merged as PR #1283

**Pull request closed without merging**
