### PR TITLE
More apex snippets

### PR DESCRIPTION
**Pull request by lukecotter**
#### What does this PR do?
Adds more snippets for apex.
Improves existing for loop snippets by adding type to the loop variable.
Improves existing while loop snippets by replacing true default value with condition.

### What issues does this PR fix or reference?
#2261

### CODE REVIEW

**Comment by ntotten** [comment]
This is great, thanks for sending! Please sign the CLA and we’ll merge right away.

**Comment by lukecotter** [comment]
> This is great, thanks for sending! Please sign the CLA and we’ll merge right away.

Sure will do. When signing do I use my primary email or can I use the private noreply email?

https://github.com/forcedotcom/salesforcedx-vscode/blob/cd9aed295be0dba835ebb4dd89e0054ff746167c/CONTRIBUTING.md

**Comment by lcampos** [comment]
@lukecotter for signing the CLA you need to use the same address used in the commits.

**Comment by lukecotter** [comment]
All done

**Comment by lcampos** [comment]
@lukecotter I'm closing this PR since we merged your changes as part of #2301 and they will be released later this week in version 48.23.0 of the extensions. Thanks for your contributions to the project.

**Pull request closed without merging**
