### PR TITLE
chore: create github release on publish

### PR DESCRIPTION
**Pull request by jgellin-sf**
### What does this PR do?
The Code Builder project will package Salesforce VSCode extensions in our container image. These are packaged as VSIX artifacts. It is possible that getting these artifacts from the VSCode Marketplace violates their terms of service, so for now we must download the artifacts manually from the appropriate CircleCI build. This PR suggests an alternative, where the extensions are published as a GitHub release as well. This would allow Code Builder to obtain these artifacts in an automated way when building the container image.

### What issues does this PR fix or reference?
N/A

### Functionality Before
In publish workflow, CircleCI publishes build artifacts only to VSCode Marketplace.

### Functionality After
In publish workflow, CircleCI publishes build artifacts to VSCode Marketplace and GitHub release.

### CODE REVIEW

**Comment by jag-sfdc** [comment]
This looks good. Are there more changes coming (since the PR is in draft)?
Curious how we plan to test this though?

**Comment by jag-sfdc** [comment]
This looks good. Are there more changes coming (since the PR is in draft)?
Curious how we plan to test this though?

**Comment by jag-sfdc** [comment]
@jgellin-sf - Got it. Let's try and include this as part of next week's release. Can we have this PR approved for now and merge it early next week (we are in the middle of an e-release now and don't want more variables)?

**Comment by jgellin-sf** [comment]
@jag-sfdc Sounds good. I've set the PR ready to review.

**Comment by jgellin-sf** [comment]
@jag-sfdc Is this one good to go?

**Review by jag-sfdc — APPROVED** [review]

**Pull request merged**
