### PR TITLE
Tbehrens/update aura command labels

### PR DESCRIPTION
**Pull request by thombehrens**
### What does this PR do?
Updates the labels for the Command Palette commands referring to first-gen lightning components, from "Lightning [Component|Interface|Event|App]" to "Aura [Component|Interface|Event|App]". Also updates references to these labels in docs & tests; does not touch api names or non-user facing references.
### What issues does this PR fix or reference?
#2189

### Functionality Before
81579810-9ac33900-937a-11ea-9397-1ec460266795

### Functionality After
Screen Shot 2020-05-14 at 11 12 05 PM
Screen Shot 2020-05-14 at 10 51 34 PM

### CODE REVIEW

**Comment by brpowell** [comment]
Thanks for your contribution @thombehrens! We'll review the changes and keep you posted on the merging process

**Comment by smaddox-sf** [comment]
Hi @thombehrens - Just a reminder that we need you to [sign the Salesforce.com Contributor License Agreement.](https://cla.salesforce.com/sign-cla?prUrl=https%3A%2F%2Fgithub.com%2Fforcedotcom%2Fsalesforcedx-vscode%2Fpull%2F2200)

**Comment by thombehrens** [comment]
Hi @smaddox-sf - I believe I hav signed the CLA- clicking the link shows me this:
DF3ACAB6-006A-43AC-9DFD-F0C9A4F0EC77

**Comment by brpowell** [comment]
@thombehrens We merged your contribution in #2221 to run the changes against our autobuilds. Thank you again and you should see the changes go out in next week's release.

**Comment by thombehrens** [comment]
Wonderful! Cheers

**Pull request closed without merging**
