### PR TITLE
Cristi/schedule e2e tests

### PR DESCRIPTION
**Pull request by CristiCanizales**
### What does this PR do?
- Adds condition to if to include runs triggered with "schedule"

### Functionality Before
- Tests being skipped in scheduled runs because if condition was missing

### Functionality After
- Tests finally running..

These runs were triggered on my fork with a workflow like the one I fixed in this PR:
- [Apex End to End Tests](https://github.com/CristiCanizales/salesforcedx-vscode-fork/actions/runs/6551352223)
- [LSP End to End Tests](https://github.com/CristiCanizales/salesforcedx-vscode-fork/actions/runs/6551359213)
- [Core End to End Tests](https://github.com/CristiCanizales/salesforcedx-vscode-fork/actions/runs/6551373889)

They're failing because I don't have the right setup on my fork (secrets and all that) but they're being run automatically as scheduled

[skip-validate-pr]

### CODE REVIEW

**Review by daphne-sfdc — APPROVED** [review]
Approved! 🎉 Thanks for getting the scheduling to work!

**Comment by diyer** [comment]
will these be run as part of nightly runs? if yes, do we get any notifications for these runs on email or slack?

**Comment by CristiCanizales** [comment]
@diyer Yes, the tests would run nightly. Regarding the notifications, right now we don't get any. Gordon was going to create a WI to address that and some other e2e details to consider.

**Comment by diyer** [comment]
@CristiCanizales qq: why do you use [skip-validate-pr] on this PR ?

**Comment by CristiCanizales** [comment]
@diyer We use that when the work/change was simple enough to not require a WI

**Pull request merged**
