### PR TITLE
fix: add new version of apex language server

### PR DESCRIPTION
**Pull request by peternhale**
Adds deadlock detection to LS

@W-14463118@

### CODE REVIEW

**Comment by diyer** [comment]
@peternhale do we get telemetry events generated for deadlocks that can help us gather data from customer usages?

**Comment by peternhale** [comment]
> @peternhale do we get telemetry events generated for deadlocks that can help us gather data from customer usages?

@diyer yes. that code is included on the Java side.

**Comment by diyer** [comment]
> > @peternhale do we get telemetry events generated for deadlocks that can help us gather data from customer usages?
> 
> @diyer yes. that code is included on the Java side.

@peternhale cool! ty. my bad, I skimmed through the [PR](https://git.soma.salesforce.com/apex/apex-jorje/pull/987/files) but did not go over in detail.

**Review by CristiCanizales — APPROVED** [review]
LGTM 👍 
QE notes [here](https://salesforce.quip.com/9MrnANOM0qPS)

**Pull request merged**
