### PR TITLE
Update jorje jar to use relative paths

### PR DESCRIPTION
**Pull request by vazexqi**
### What does this PR do?

Changes the way we store the system classes in the database to no longer hard-code the paths.

### What issues does this PR fix or reference?

@W-4199304@

### CODE REVIEW

**Comment by vazexqi** [comment]
One of the Travis-CI builds timed out. @Sweetman - what did you say was the way to run it again to prevent flakiness? This is a fresh PR with only one commit to it.

Merging based on the results from the other autobuilds.

**Comment by guw** [comment]
@vazexqi You should see a "restart" build button on the Travis CI build for this particular build.

**Comment by vazexqi** [comment]
@guw I know how to restart it but I would like to know if there is a way to submit PRs so that we have less flakiness from the autobuild. So far the Appveyor one seems more stable than the Travis one. Is there something we need to do on the tests or is this just an inherent problem with the Travis service? You've used them before so I'm curious what your experiences are.

**Comment by guw** [comment]
I've never experienced the level of flakiness before. Frankly, Linux builds usually run fine. However, I've never run UI tests before on Travis. I think it maybe related to UI testing under Linux. We need to monitor this, though.

**Comment by Sweetman** [comment]
@vazexqi Missed your notification. I wasn't able to find the reason why the builds flake but it seemed like by making sure that the branch was rebased to the latest on develop, the PR doesn't flake.

**Pull request merged**
