### PR TITLE
Update docs for rename refactoring

### PR DESCRIPTION
**Pull request by praksb**
### What does this PR do?
Add documentation for rename refactoring.

### What issues does this PR fix or reference?
Update README.md to include some gifs and documentation for Rename refactoring.

@W-5793239@

### CODE REVIEW

**Comment by praksb** [comment]
@ruthemmanuelle Your changes looks good!

**Comment by lcampos** [comment]
@praksb this will add 5+ MB more to a vsix that's already 28MB. Can we reduce the size of those gifs before getting this merged ?

**Comment by praksb** [comment]
@lcampos I'll sync up with you tomorrow on the gif file size.

**Comment by praksb** [comment]
@lcampos Can you review my latest commit? I moved the gifs to the top-level folder and updated the link in README.md file.

**Pull request merged**
