### PR TITLE
Soql Builder Release - Custom Select plus WHERE Clause

### PR DESCRIPTION
**Pull request by dehru**
### What does this PR do?

This PR releases the custom-select component we built using LWC for the Soql Builder UI.

### What issues does this PR fix or reference?
@W-8616120@
@W-8616118@

### Functionality Before

A big giant ugly default html select element.

Screen Shot 2021-02-01 at 4 00 23 PM

### Functionality After
A searchable version written in LWC.

https://user-images.githubusercontent.com/599418/106529018-fe603a00-64a6-11eb-99e8-afc001aeec27.mov

### CODE REVIEW

**Comment by praksb** [comment]
I think as part of this PR we should also update: https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-soql/README.md to reflect the new UI.

FYI: @ekapner

**Comment by dehru** [comment]
@dobladez - I didn't bump the version of the soql-language-server.  Lemme know if we should.  I think you are waiting on some downstream changes...

**Comment by dobladez** [comment]
> @dobladez - I didn't bump the version of the soql-language-server. Lemme know if we should. I think you are waiting on some downstream changes...

No, no need.

**Comment by dehru** [comment]
I'm closing this PR. Emily already has some doc work ready to push into the other release PR here: https://github.com/forcedotcom/salesforcedx-vscode/pull/2896

**Pull request closed without merging**
