### PR TITLE
Verify vscode:package as part of autobuilds

### PR DESCRIPTION
**Pull request by chowwinston**
### What does this PR do?
Add vscode:package for appveyor and travis so we can verify the ability to package

### CODE REVIEW

**Comment by chowwinston** [comment]
Putting this in as a separate commit to develop since the release branch's autobuild results were a bit flaky. Let's monitor and see what happens

**Comment by DatGuyJonathan** [comment]
@chowwinston Could you rebase with develop so we get the fix for types/node? It seems packaging on Windows can be flaky. I'm wondering if the Linux build is more reliable.

**Comment by chowwinston** [comment]
@DatGuyJonathan are you ok with closing this PR? It's too flaky to be worthwhile for the builds. Maybe we can consider keeping appveyor since that one seems the most stable.

**Comment by DatGuyJonathan** [comment]
Sure, let's try just having appveyor package for now.

**Pull request merged**
