### PR TITLE
Show persisted variable expansion in GIF

### PR DESCRIPTION
**Pull request by ruthemmanuelle**
### What does this PR do?
Updates GIF for salesforcedx-apex-debugger to include Gunnar's fix for [https://github.com/Microsoft/vscode/issues/16031](https://github.com/Microsoft/vscode/issues/16031).

The new GIF will show in the README after this week's branch is merged back into `develop`.

### What issues does this PR fix or reference?
@W-4349628@

### CODE REVIEW

**Comment by vazexqi** [comment]
@DatGuyJonathan - Since we didn't mention anything about using the VS Code Insiders version (that contains the fix), should this be merged in for release tomorrow or when VS Code 1.18 is available officially?

**Comment by guw** [comment]
@vazexqi I think it should be merged in now. There is no harm in showing it. The debugger can only be installed into 1.18 anyway.

**Comment by vazexqi** [comment]
The debugger can only be installed into 1.18 anyway.

Wait. That doesn't make sense. 1.18 is not released yet. Did we mistakenly specify 1.18 as a requirement?

**Comment by guw** [comment]
I stand corrected - 1.17.2 (just tested). Looks like I had a Code install of 1.16 when I tried it earlier this morning.

**Comment by ruthemmanuelle** [comment]
The README says the extensions all require v1.17 or later. Should we update it to 1.17.2 for some or all extensions?

**Comment by vazexqi** [comment]
@ruthemmanuelle keeping it as "v1.17 or later." is OK.

I'm just waiting for @DatGuyJonathan's decision on when this should be merged in. If we don't put this in this week, then it will go out on Nov 16, which might coincide better with when VS Code 1.18 (not the insiders version) goes out.

**Comment by DatGuyJonathan** [comment]
I prefer waiting until 1.18 is official. An option is to create a Git issue about it and mention it is fixed in the insiders version.

**Comment by ruthemmanuelle** [comment]
Ok. I'd thought from our conversation in standup that you guys wanted to get this in right away, but waiting is fine. If I have time I'll create a more polished GIF than the one in this PR.

**Comment by vazexqi** [comment]
VS Code 1.18 was released yesterday so @ruthemmanuelle if you want to create a more polished gif and upload it that would be good.

**Pull request merged**
