### PR TITLE
SObject integration using the jsforce library

### PR DESCRIPTION
**Pull request by jgellin-sf**
### What does this PR do?
This PR uses the jsforce library's describe API to retrieve SObject metadata rather than using the `sobject-metadata` library.

### What issues does this PR fix or reference?
@W-8100182@

### Functionality Before
The SOQL extension retrieves SObject metadata from a connected org using the `sobject-metadata` library API.

### Functionality After
The SOQL extension retrieves SObject metadata from a connected org using the `jsforce` library API.

### CODE REVIEW

**Review by dobladez — APPROVED** [review]
LGTM

**Comment by jgellin-sf** [comment]
> Could we add `jsforce` to the `dependencies` field in package.json?

@xyc I don't think so. I added `jsforce` and got the following compiler problems: 
```
salesforcedx-vscode-soql: src/editor/soqlEditorInstance.ts(157,34): error TS2345: Argument of type 'import(".../salesforcedx-vscode/packages/salesforcedx-vscode-soql/node_modules/@salesforce/core/node_modules/@types/jsforce/describe-result").DescribeSObjectResult' is not assignable to parameter of type 'import(".../salesforcedx-vscode/packages/salesforcedx-vscode-soql/node_modules/@types/jsforce/describe-result").DescribeSObjectResult'.
```
The `jsforce` library is accessed indirectly through the `@salesforce/core` Connection object obtained from the extension dependency on `salesforcedx-vscode-core`. Even though the two `DescribeSObjectResult` definitions above are identical, they are not assignable.

**Comment by xyc** [comment]
@jgellin-sf You might also want to add `@types/jsforce` as a dev dependency. 

Circle CI build isn't passing:
salesforcedx-vscode-soql: src/editor/soqlEditorInstance.ts(8,28): error TS2307: Cannot find module '@salesforce/core'.
salesforcedx-vscode-soql: src/editor/soqlEditorInstance.ts(10,39): error TS2307: Cannot find module 'jsforce'.
salesforcedx-vscode-soql: src/editor/soqlEditorInstance.ts(149,9): error TS7006: Parameter 'sobject' implicitly has an 'any' type.

**Review by praksb — APPROVED** [review]

**Comment by jgellin-sf** [comment]
@xyc It took some time but now I'm able to reproduce this same problem. I couldn't understand how `@salesforce/core` was getting into the soql extension's `node_modules` when I'm cleaning and rebuilding. I thought it was some weird node/vscode bootstrap script magic. It turns out there simply was no `clean` script in the soql extension and I was working with some leftover modules the whole time. 🤦‍♂️ The latest commit should fix things.

**Review by xyc — APPROVED** [review]
@jgellin-sf No problem! It's tricky that `clean` script is missing, glad you find it out :)

**Review by dehru — APPROVED** [review]
I tested this against the latest soql-builder-ui and i am getting sobjects and metadata.

**Pull request merged**
