### PR TITLE
Add config flag to retrieve code coverage when running unit tests.

### PR DESCRIPTION
**Pull request by dylanribb**
### What does this PR do?
Adds a configuration flag indicating whether code coverage should be retrieved when running Apex Unit Tests.

### What issues does this PR fix or reference?
#473
@W-5083565@

### CODE REVIEW

**Comment by dylanribb** [comment]
screen shot 2018-06-11 at 5 20 26 pm

See screenshot above for how the flag and description appear in the Settings file.

**Comment by vazexqi** [comment]
@dylanribb - Thanks for the PR. I think this approach looks reasonable. I'll discuss with the team.

Could you do two things:

1) Could you run scripts/reformat-with-prettier.js? The format for the package.json look weird.
2) Are you comfortable with rebasing? You have only two main commits, but the merge history looks like it's merging many things in.

Both would help keep the PR focused.

**Comment by dylanribb** [comment]
> Could you run scripts/reformat-with-prettier.js? The format for the package.json look weird.

I will gladly do that. I ran into some weird conflicts with my own extensions and the ones VS Code recommended. I'll reformat and resubmit.

> Are you comfortable with rebasing? You have only two main commits, but the merge history looks like it's merging many things in.

I haven't done a whole lot of rebasing but I can do some research and try to get the history cleaned up a bit (if you have any suggestions/tips I'm open to hearing them).

**Comment by dylanribb** [comment]
@vazexqi Sounds good. I ran the format scripts and reuploaded.

**Comment by vazexqi** [comment]
- [ ] Need to format the package.json (one more file seems to be  in a wrong format).
- [ ] Need to cherry-pick and rebase changes
- [ ] Verify language
- [ ] Verify if this preference will also be picked up by the Apex Language Server for the code lens

**Pull request closed without merging**
