### PR TITLE
Remove unnecessary check for number of files created in e2e tests

### PR DESCRIPTION
**Pull request by Sweetman**
### What does this PR do?
Removes part of integration tests verifying that the number of files created is correct. This would be an issue that the CLI command should test and handle.
### What issues does this PR fix or reference?
@W-4271774@

### CODE REVIEW

**Comment by vazexqi** [comment]
LGTM. Let's see if the CI system, in particular, AppVeyor, likes this better.

**Comment by vazexqi** [comment]
@Sweetman - Anything preventing us from merging this in? Are you still experimenting with other autobuild configurations?

**Comment by Sweetman** [comment]
No, I will merge it in. Need to rebase the branch to latest and then I'll merge once it lets me

**Comment by vazexqi** [comment]
@Sweetman - I'm going to merge this in.

I can reproduce the issue with counting the elements on my local Windows pretty consistently. This is more of a testing issue. I don't think you can just count how many elements show up in the quick open list (without some sort of loop-and-wait).

**Pull request merged**
